### ISSUE TITLE
Finish converting old static files to Jekyll/Markdown

### ISSUE THREAD

**Issue by chimericdream** [chimericdream/worldofpannotia.com#1]
- [x] Game Rules // Basics
- [x] Game Rules // Races // Overview
- [x] Game Rules // Classes // Base Classes
- [x] Game Rules // Classes // Prestige Classes
- [x] Game Rules // Classes // Epic Classes
- [x] Game Rules // Classes // Racial Classes
- [x] Game Rules // Classes // NPC Classes
- [x] Game Rules // Classes // Multiclass Characters
- [x] Game Rules // Skills // Overview
- [x] Game Rules // Skills // Using Skills
- [x] Game Rules // Skills // Descriptions
- [x] Game Rules // Skills // Epic Skill Uses
- [x] Game Rules // Feats // Overview
- [x] Game Rules // Feats // Descriptions
- [x] Game Rules // Feats // Feat Lists // General
- [x] Game Rules // Feats // Feat Lists // Fighter
- [x] Game Rules // Feats // Feat Lists // Item Creation
- [x] Game Rules // Feats // Feat Lists // Metamagic
- [x] Game Rules // Feats // Feat Lists // Metapsionic
- [x] Game Rules // Feats // Feat Lists // Psionic
- [x] Game Rules // Feats // Feat Lists // Divine
- [x] Game Rules // Feats // Feat Lists // Monster
- [x] Game Rules // Feats // Feat Lists // Epic
- [x] Game Rules // Feats // Feat Index
- [x] Game Rules // Magic // Overview
- [x] Game Rules // Magic // Spell Descriptions
- [x] Game Rules // Magic // Arcane Spells
- [x] Game Rules // Magic // Divine Spells
- [x] Game Rules // Magic // Spell Index
- [x] Game Rules // Magic // Domains
- [x] Game Rules // Magic // Spell Lists // Bard
- [x] Game Rules // Magic // Spell Lists // Cleric
- [x] Game Rules // Magic // Spell Lists // Druid
- [x] Game Rules // Magic // Spell Lists // Paladin
- [x] Game Rules // Magic // Spell Lists // Ranger
- [x] Game Rules // Magic // Spell Lists // Sorcerer/Wizard
- [x] Game Rules // Magic // Spell Combinations // Spell Combination Index
- [x] Game Rules // Magic // Epic Spells // Overview
- [x] Game Rules // Magic // Epic Spells // Developing Epic Spells
- [x] Game Rules // Magic // Epic Spells // Seeds
- [x] Game Rules // Magic // Epic Spells // Epic Spell Index
- [x] Game Rules // Psionics // Overview
- [x] Game Rules // Psionics // Power Descriptions
- [x] Game Rules // Psionics // Power Index
- [x] Game Rules // Psionics // Power Lists // Psion/Wilder
- [x] Game Rules // Psionics // Power Lists // Psychic Warrior
- [x] Game Rules // Psionics // Epic Powers
- [x] Game Rules // Adventuring // Combat // Overview
- [x] Game Rules // Adventuring // Combat // Mechanics
- [x] Game Rules // Adventuring // Combat // Initiative
- [x] Game Rules // Adventuring // Combat // Attacks of Opportunity
- [x] Game Rules // Adventuring // Combat // Combat Actions
- [x] Game Rules // Adventuring // Combat // Injury & Death
- [x] Game Rules // Adventuring // Combat // Movement
- [x] Game Rules // Adventuring // Combat // Combat Modifiers
- [x] Game Rules // Adventuring // Combat // Special Attacks
- [x] Game Rules // Adventuring // Special Abilities // Overview
- [x] Game Rules // Adventuring // Special Abilities // Descriptions
- [x] Game Rules // Adventuring // Status Conditions
- [x] Game Rules // Adventuring // Carrying, Movement, & Exploration // Carrying Capacity
- [x] Game Rules // Adventuring // Carrying, Movement, & Exploration // Movement
- [x] Game Rules // Adventuring // Carrying, Movement, & Exploration // Exploration
- [x] Game Rules // Adventuring // Wilderness & Environment // Dungeons
- [x] Game Rules // Adventuring // Wilderness & Environment // Wilderness
- [x] Game Rules // Adventuring // Wilderness & Environment // Weather
- [x] Game Rules // Adventuring // Wilderness & Environment // The Environment
- [x] Game Rules // Adventuring // Traps // Overview
- [x] Game Rules // Adventuring // Traps // Designing a Trap
- [x] Game Rules // Adventuring // Traps // Sample
- [x] Game Rules // Divine Rules // Divine Ranks
- [x] Game Rules // Divine Rules // Divine Characteristics
- [x] Game Rules // Divine Rules // Salient Divine Abilities
- [x] Game Rules // Divine Rules // Divine Minions
- [x] Equipment // Wealth & Money
- [x] Equipment // Goods & Services // Adventuring Gear
- [x] Equipment // Goods & Services // Special Substances & Items
- [x] Equipment // Goods & Services // Tools & Skill Sets
- [x] Equipment // Goods & Services // Clothing
- [x] Equipment // Goods & Services // Food, Drink, & Lodging
- [x] Equipment // Goods & Services // Mounts & Related Gear
- [x] Equipment // Goods & Services // Transport
- [x] Equipment // Goods & Services // Spellcasting & Services
- [x] Equipment // Special Materials
- [x] Equipment // Armor // Overview
- [x] Equipment // Armor // Armor Descriptions
- [x] Equipment // Weapons // Overview
- [x] Equipment // Weapons // Weapon Descriptions
- [x] Equipment // Magic Items // Overview
- [x] Equipment // Magic Items // Creating Magic Items
- [x] Equipment // Magic Items // Armor // Overview
- [x] Equipment // Magic Items // Armor // Armor Abilities
- [x] Equipment // Magic Items // Armor // Specific Armor
- [x] Equipment // Magic Items // Weapons // Overview
- [x] Equipment // Magic Items // Weapons // Weapon Abilities
- [x] Equipment // Magic Items // Weapons // Specific Weapons
- [x] Equipment // Magic Items // Potions & Oils // Overview
- [x] Equipment // Magic Items // Potions & Oils // Descriptions
- [x] Equipment // Magic Items // Rings // Overview
- [x] Equipment // Magic Items // Rings // Descriptions
- [x] Equipment // Magic Items // Rods // Overview
- [x] Equipment // Magic Items // Rods // Descriptions
- [x] Equipment // Magic Items // Scrolls // Overview
- [x] Equipment // Magic Items // Scrolls // Descriptions
- [x] Equipment // Magic Items // Staffs // Overview
- [x] Equipment // Magic Items // Staffs // Descriptions
- [x] Equipment // Magic Items // Wands // Overview
- [x] Equipment // Magic Items // Wands // Descriptions
- [x] Equipment // Magic Items // Wondrous Items // Overview
- [x] Equipment // Magic Items // Wondrous Items // Descriptions
- [x] Equipment // Psionic Items // Overview
- [x] Equipment // Psionic Items // Creating Psionic Items
- [x] Equipment // Psionic Items // Armor // Overview
- [x] Equipment // Psionic Items // Armor // Armor Abilities
- [x] Equipment // Psionic Items // Weapons // Overview
- [x] Equipment // Psionic Items // Weapons // Weapon Abilities
- [x] Equipment // Psionic Items // Cognizance Crystals // Overview
- [x] Equipment // Psionic Items // Cognizance Crystals // Descriptions
- [x] Equipment // Psionic Items // Dorjes // Overview
- [x] Equipment // Psionic Items // Dorjes // Descriptions
- [x] Equipment // Psionic Items // Power Stones // Overview
- [x] Equipment // Psionic Items // Power Stones // Descriptions
- [x] Equipment // Psionic Items // Psicrowns // Overview
- [x] Equipment // Psionic Items // Psicrowns // Descriptions
- [x] Equipment // Psionic Items // Psionic Tattoos // Overview
- [x] Equipment // Psionic Items // Psionic Tattoos // Descriptions
- [x] Equipment // Psionic Items // Universal Items // Overview
- [x] Equipment // Psionic Items // Universal Items // Descriptions
- [x] Equipment // Epic Magic Items // Overview
- [x] Equipment // Epic Magic Items // Armor // Overview
- [x] Equipment // Epic Magic Items // Armor // Armor Abilities
- [x] Equipment // Epic Magic Items // Armor // Specific Armor
- [x] Equipment // Epic Magic Items // Weapons // Overview
- [x] Equipment // Epic Magic Items // Weapons // Weapon Abilities
- [x] Equipment // Epic Magic Items // Weapons // Specific Weapons
- [x] Equipment // Epic Magic Items // Rings
- [x] Equipment // Epic Magic Items // Rods
- [x] Equipment // Epic Magic Items // Scrolls
- [x] Equipment // Epic Magic Items // Staffs
- [x] Equipment // Epic Magic Items // Wondrous Items
- [x] Equipment // Intelligent Items // Overview
- [x] Equipment // Intelligent Items // Epic Intelligent Items // Overview
- [x] Equipment // Cursed Items // Overview
- [x] Equipment // Cursed Items // Descriptions
- [x] Equipment // Artifacts // Overview
- [x] Equipment // Artifacts // Minor Artifacts
- [x] Equipment // Artifacts // Major Artifacts
- [x] Monsters // Introduction
- [x] Monsters // Types & Subtypes
- [x] Monsters // Improving Monsters
- [x] Monsters // Entries // Monsters
- [x] Monsters // Entries // Animals
- [x] Monsters // Entries // Vermin
- [x] Monsters // Templates // Overview
- [x] Monsters // Templates // Template Index
- [x] Setting // Geography // World Map
- [x] Setting // Geography // Regions & Countries
- [x] Setting // Geography // Cities
- [x] Setting // Cosmology // Overview
- [x] Setting // Cosmology // Planar Traits
- [x] Setting // Religion // Deities
- [x] Setting // Religion // The Divine Tournament // Introduction
- [x] Misc // Credits
- [x] Misc // Open Game License
