### ISSUE TITLE
Monsters and templates

### ISSUE THREAD

**Issue by chimericdream** [chimericdream/worldofpannotia.com#49]
This should be done after #34 is complete, or there will be some duplicate effort.
#### Monsters/Templates
- [ ] Aboleth
  - [ ] Aboleth Mage
- [ ] Achaierai
- [ ] Allip
- [ ] Angel
  - [ ] Angel, Astral Deva
  - [ ] Angel, Planetar
  - [ ] Angel, Solar
- [ ] Animated Object
- [ ] Ankheg
- [ ] Aranea
- [ ] Archon
  - [ ] Lantern Archon
  - [ ] Hound Archon
    - [ ] Hound Archon Hero
  - [ ] Trumpet Archon
- [ ] Arrowhawk
- [ ] Assassin Vine
- [ ] Athach
- [ ] Avoral
- [ ] Azer
- [ ] Barghest
  - [ ] Greater Barghest
- [ ] Basilisk
  - [ ] Abyssal Greater Basilisk
- [ ] Behir
- [ ] Belker
- [ ] Blink Dog
- [ ] Bodak
- [ ] Bralani
- [ ] Bugbear
- [ ] Bulette
- [ ] Celestial Creature
- [ ] Centaur
- [ ] Chaos Beast
- [ ] Chimera
- [ ] Choker
- [ ] Chuul
- [ ] Cloaker
- [ ] Cockatrice
- [ ] Couatl
- [ ] Darkmantle
- [ ] Delver
- [ ] Demon
  - [ ] Babau
  - [ ] Balor
  - [ ] Bebilith
  - [ ] Dretch
  - [ ] Glabrezu
  - [ ] Hezrou
  - [ ] Marilith
  - [ ] Nalfeshnee
  - [ ] Quasit
  - [ ] Retriever
  - [ ] Succubus
  - [ ] Vrock
- [ ] Derro
- [ ] Destrachan
- [ ] Devil
  - [ ] Barbed Devil (Hamatula)
  - [ ] Bearded Devil (Barbazu)
  - [ ] Bone Devil (Osyluth)
  - [ ] Chain Devil (Kyton)
  - [ ] Erinyes
  - [ ] Hellcat (Bezekira)
  - [ ] Horned Devil (Cornugon)
  - [ ] Ice Devil (Gelugon)
  - [ ] Imp
  - [ ] Lemure
  - [ ] Pit Fiend
- [ ] Devourer
- [ ] Digester
- [ ] Dinosaur
  - [ ] Deinonychus
  - [ ] Elasmosaurus
  - [ ] Megaraptor
  - [ ] Triceratops
  - [ ] Tyrannosaurus
- [ ] Dire Animal
  - [ ] Dire Ape
  - [ ] Dire Badger
  - [ ] Dire Bat
  - [ ] Dire Bear
  - [ ] Dire Boar
  - [ ] Dire Lion
  - [ ] Dire Rat
  - [ ] Dire Shark
  - [ ] Dire Tiger
  - [ ] Dire Weasel
  - [ ] Dire Wolf
  - [ ] Dire Wolverine
- [ ] Doppelganger
- [ ] Dragon, True
  - [ ] Chromatic Dragons
    - [ ] Black Dragon
    - [ ] Blue Dragon
    - [ ] Green Dragon
    - [ ] Red Dragon
    - [ ] White Dragon
  - [ ] Metallic Dragons
    - [ ] Brass Dragon
    - [ ] Bronze Dragon
    - [ ] Copper Dragon
    - [ ] Gold Dragon
    - [ ] Silver Dragon
- [ ] Dragon Turtle
- [ ] Dragonne
- [ ] Drider
- [ ] Dryad
- [ ] Dwarf
  - [ ] Deep Dwarf
  - [ ] Duergar
  - [ ] Mountain Dwarf
- [ ] Eagle, Giant
- [ ] Elemental
  - [ ] Air Elemental
  - [ ] Earth Elemental
  - [ ] Fire Elemental
  - [ ] Water Elemental
- [ ] Elf
  - [ ] Half-Elf
  - [ ] Aquatic Elf
  - [ ] Drow
  - [ ] Gray Elf
  - [ ] Wild Elf
  - [ ] Wood Elf
- [ ] Ethereal Filcher
- [ ] Ethereal Marauder
- [ ] Ettercap
- [ ] Ettin
- [ ] Fiendish Creature
- [ ] Formian
  - [ ] Worker
  - [ ] Warrior
  - [ ] Taskmaster
  - [ ] Myrmarch
  - [ ] Queen
- [ ] Frost Worm
- [ ] Fungus
  - [ ] Shrieker
  - [ ] Violet Fungus
- [ ] Gargoyle
  - [ ] Kapoacinth
- [ ] Genie
  - [ ] Djinni
    - [ ] Noble Djinn
  - [ ] Efreeti
  - [ ] Janni
- [ ] Ghaele
- [ ] Ghost
- [ ] Ghoul
  - [ ] Lacedon
  - [ ] Ghast
- [ ] Giant
  - [ ] Cloud Giant
  - [ ] Fire Giant
  - [ ] Frost Giant
    - [ ] Frost Giant Jarl
  - [ ] Hill Giant
  - [ ] Stone Giant
    - [ ] Stone Giant Elders
  - [ ] Storm Giant
- [ ] Gibbering Mouther
- [ ] Girallon
- [ ] Gnoll
- [ ] Gnome
  - [ ] Svirfneblin
  - [ ] Forest Gnome
- [ ] Goblin
- [ ] Golem
  - [ ] Clay Golem
  - [ ] Flesh Golem
  - [ ] Iron Golem
  - [ ] Stone Golem
    - [ ] Greater Stone Golem
- [ ] Gorgon
- [ ] Gray Render
- [ ] Grick
- [ ] Griffon
- [ ] Grimlock
- [ ] Hag
  - [ ] Annis
  - [ ] Green Hag
  - [ ] Sea Hag
- [ ] Half-Celestial
- [ ] Half-Dragon
- [ ] Half-Fiend
- [ ] Halfling
  - [ ] Tallfellow
  - [ ] Deep Halfling
- [ ] Harpy
  - [ ] Harpy Archer
- [ ] Hell Hound
  - [ ] Nessian Warhound
- [ ] Hippogriff
- [ ] Hobgoblin
- [ ] Homunculus
- [ ] Howler
- [ ] Hydra
  - [ ] Pyrohydra
  - [ ] Cryohydra
- [ ] Inevitable
  - [ ] Kolyarut
  - [ ] Marut
  - [ ] Zelekhut
- [ ] Invisible Stalker
- [ ] Kobold
- [ ] Kraken
- [ ] Krenshar
- [ ] Lamia
- [ ] Lammasu
  - [ ] Golden Protector
- [ ] Leonal
- [ ] Lich
- [ ] Lillend
- [ ] Lizardfolk
- [ ] Locathah
- [ ] Lycanthrope
  - [ ] Werebear
  - [ ] Wereboar
    - [ ] Hill Giant Dire Wereboar
  - [ ] Wererat
  - [ ] Weretiger
  - [ ] Werewolf
    - [ ] Werewolf Lord
- [ ] Magmin
- [ ] Manticore
- [ ] Medusa
- [ ] Mephit
  - [ ] Air Mephit
  - [ ] Dust Mephit
  - [ ] Earth Mephit
  - [ ] Fire Mephit
  - [ ] Ice Mephit
  - [ ] Magma Mephit
  - [ ] Ooze Mephit
  - [ ] Salt Mephit
  - [ ] Steam Mephit
  - [ ] Water Mephit
- [ ] Merfolk
- [ ] Mimic
- [ ] Minotaur
- [ ] Mohrg
- [ ] Mummy
  - [ ] Mummy Lord
- [ ] Naga
  - [ ] Dark Naga
  - [ ] Guardian Naga
  - [ ] Spirit Naga
  - [ ] Water Naga
- [ ] Night Hag
- [ ] Nightmare
  - [ ] Cauchemar
- [ ] Nightshade
  - [ ] Nightcrawler
  - [ ] Nightwalker
  - [ ] Nightwing
- [ ] Nymph
- [ ] Ogre
  - [ ] Ogre Barbarian
  - [ ] Merrow
- [ ] Ogre Mage
- [ ] Ooze
  - [ ] Black Pudding
    - [ ] Elder Black Pudding
  - [ ] Gelatinous Cube
  - [ ] Gray Ooze
  - [ ] Ochre Jelly
- [ ] Orc
  - [ ] Half-Orcs
- [ ] Otyugh
- [ ] Owl, Giant
- [ ] Owlbear
- [ ] Pegasus
- [ ] Phantom Fungus
- [ ] Phase Spider
- [ ] Phasm
- [ ] Planetouched
  - [ ] Aasimar
  - [ ] Tiefling
- [ ] Pseudodragon
- [ ] Purple Worm
- [ ] Rakshasa
- [ ] Rast
- [ ] Ravid
- [ ] Razor Boar
- [ ] Remorhaz
- [ ] Roc
- [ ] Roper
- [ ] Rust Monster
- [ ] Sahuagin
  - [ ] Sahuagin Mutants
    - [ ] Malenti
- [ ] Salamander
- [ ] Satyr
- [ ] Scorpionfolk
- [ ] Sea Cat
- [ ] Shadow
  - [ ] Greater Shadow
- [ ] Shadow Mastiff
- [ ] Shambling Mound
- [ ] Shield Guardian
- [ ] Shocker Lizard
- [ ] Skeleton
- [ ] Skum
- [ ] Spectre
- [ ] Sphinx
  - [ ] Androsphinx
  - [ ] Criosphinx
  - [ ] Gynosphinx
  - [ ] Hieracosphinx
- [ ] Spider Eater
- [ ] Sprite
  - [ ] Grig
  - [ ] Nixie
  - [ ] Pixie
- [ ] Stirge
- [ ] Swarm
  - [ ] Bat Swarm
  - [ ] Centipede Swarm
  - [ ] Hellwasp Swarm
  - [ ] Locust Swarm
  - [ ] Rat Swarm
  - [ ] Spider Swarm
- [ ] Tarrasque
- [ ] Tendriculos
- [ ] Thoqqua
- [ ] Titan
- [ ] Tojanida
- [ ] Treant
- [ ] Triton
- [ ] Troglodyte
- [ ] Troll
  - [ ] Scrag
  - [ ] Troll Hunter
- [ ] Unicorn
  - [ ] Celestial Charger
- [ ] Vampire
  - [ ] Vampire Spawn
- [ ] Vargouille
- [ ] Wight
- [ ] Will-O'-Wisp
- [ ] Winter Wolf
- [ ] Worg
- [ ] Wraith
  - [ ] Dread Wraith
- [ ] Wyvern
- [ ] Xill
- [ ] Xorn
- [ ] Yeth Hound
- [ ] Yrthak
- [ ] Zombie
#### Animals
- [ ] Ape
- [ ] Baboon
- [ ] Badger
- [ ] Bat
- [ ] Bear, Black
- [ ] Bear, Brown
- [ ] Bear, Polar
- [ ] Bison
- [ ] Boar
- [ ] Camel
- [ ] Cat
- [ ] Cheetah
- [ ] Crocodile
- [ ] Crocodile, Giant
- [ ] Dog
- [ ] Dog, Riding
- [ ] Donkey
- [ ] Eagle
- [ ] Elephant
- [ ] Hawk
- [ ] Horse
  - [ ] Horse, Heavy
  - [ ] Horse, Light
  - [ ] Warhorse, Heavy
  - [ ] Warhorse, Light
- [ ] Hyena
- [ ] Leopard
- [ ] Lion
- [ ] Lizard
- [ ] Lizard, Monitor
- [ ] Manta Ray
- [ ] Monkey
- [ ] Mule
- [ ] Octopus
- [ ] Octopus, Giant
- [ ] Owl
- [ ] Pony
- [ ] Pony, War
- [ ] Porpoise
- [ ] Rat
- [ ] Raven
- [ ] Rhinoceros
- [ ] Shark
- [ ] Snake
  - [ ] Constrictor Snake
  - [ ] Viper Snake
- [ ] Squid
- [ ] Squid, Giant
- [ ] Tiger
- [ ] Toad
- [ ] Weasel
- [ ] Whale
  - [ ] Baleen Whale
  - [ ] Cachalot Whale
  - [ ] Orca
- [ ] Wolf
- [ ] Wolverine
#### Vermin
- [ ] Giant Ant
- [ ] Giant Bee
- [ ] Giant Bombardier Beetle
- [ ] Giant Fire Beetle
- [ ] Giant Stag Beetle
- [ ] Giant Praying Mantis
- [ ] Giant Wasp
- [ ] Monstrous Centipede
- [ ] Monstrous Scorpion
- [ ] Monstrous Spider
#### Divine Minions
- [ ] Petitioners
#### Psionic Monsters
- [ ] Aboleth, Psionic
- [ ] Astral Construct
- [ ] Blue
- [ ] Brain Mole
- [ ] Caller In Darkness
- [ ] Cerebrilith
- [ ] Couatl, Psionic
- [ ] Crysmal
- [ ] Dromite
- [ ] Duergar, Psionic
- [ ] Elan
- [ ] Folugub
- [ ] Gray Glutton
- [ ] Half-Giant
- [ ] Intellect Devourer
- [ ] Maenad
- [ ] Neothelid
- [ ] Phrenic Creature
- [ ] Phthisic
- [ ] Psicrystal
- [ ] Psion-Killer
- [ ] Puppeteer
  - [ ] Puppeteer, Flesh Harrower
- [ ] Temporal Filcher
- [ ] Thought Eater
- [ ] Thought Slayer
- [ ] Udoroot
- [ ] Unbodied
- [ ] Xeph
#### Epic Monsters
- [ ] Abomination
  - [ ] Anaxim
  - [ ] Atropal
  - [ ] Chichimec
  - [ ] Dream Larva
  - [ ] Hecatoncheires
  - [ ] Infernal
  - [ ] Phaethon
  - [ ] Phane
  - [ ] Xixecal
- [ ] Behemoth
  - [ ] Behemoth Eagle
  - [ ] Behemoth Gorilla
- [ ] Brachyurus
- [ ] Colossus
  - [ ] Stone Colossus
  - [ ] Flesh Colossus
  - [ ] Iron Colossus
- [ ] Demilich
- [ ] Devastation Vermin
  - [ ] Devastation Centipede
  - [ ] Devastation Spider
  - [ ] Devastation Scorpion
  - [ ] Devastation Beetle
- [ ] Dragon, Advanced
- [ ] Dragon, Epic
  - [ ] Force Dragon
  - [ ] Prismatic Dragon
- [ ] Elemental, Primal
  - [ ] Primal Air Elemental
  - [ ] Primal Earth Elemental
  - [ ] Primal Fire Elemental
  - [ ] Primal Water Elemental
- [ ] Genius Loci
- [ ] Gibbering Orb
- [ ] Gloom
- [ ] Golem
  - [ ] Mithral Golem
  - [ ] Adamantine Golem
- [ ] Ha-Naga
- [ ] Hagunemnon (Protean)
- [ ] Hoary Hunter
  - [ ] Hoary Steed
- [ ] Hunefer
- [ ] Lavawight
- [ ] Legendary Animal
  - [ ] Legendary Bear
  - [ ] Legendary Tiger
- [ ] leShay
- [ ] Living Vault
- [ ] Mercane
- [ ] Mu Spore
- [ ] Neh-Thalggu (Brain Collector)
- [ ] Paragon Creature
- [ ] Prismasaurus
- [ ] Pseudonatural Creature
  - [ ] Pseudonatural Troll
- [ ] Ruin Swarm
- [ ] Shadow Of The Void
- [ ] Shape Of Fire
- [ ] Sirrush
  - [ ] Three-Headed Sirrush
- [ ] Tayellah
- [ ] Thorciasid
- [ ] Titan, Elder
- [ ] Treant, Elder
- [ ] Umbral Blot (Blackball)
- [ ] Uvuudaum
- [ ] Vermiurge
- [ ] Winterwight
- [ ] Worm That Walks
