### ISSUE TITLE
Typography cleanup. #pedantic

### ISSUE THREAD

**Issue by chimericdream** [chimericdream/worldofpannotia.com#5]
- [ ] Use "&ndash;" and "&mdash;" where appropriate ([Reference](http://en.wikipedia.org/wiki/Dash))
- [ ] Use " &#8725; " for [vulgar fractions](http://en.wikipedia.org/wiki/Fraction_%28mathematics%29#Simple.2C_common.2C_or_vulgar_fractions) (e.g. " <sup>123</sup>&#8725;<sub>456</sub> ") ([Reference](http://en.wikipedia.org/wiki/Slash_%28punctuation%29))
- [ ] Use numerical superscripts for notes in tables (rather than *, &dagger;, &Dagger;, etc.)
- [ ] Use "&hellip;" (ellipsis) instead of "..." (three periods)
